name: Xcode Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build-test-package:
    name: Build & Test Package
    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=macOS,arch=x86_64,variant=Mac Catalyst
          - name=iPhone 14
          - name=Apple TV
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild \
          -scheme FHPropertyWrappers \
          -destination '${{ matrix.destination }}'
      - name: Test 
        run: |
          xcodebuild \
          -scheme FHPropertyWrappers \
          -destination '${{ matrix.destination }}' \
          test
