name: Xcode Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme FHPropertyWrappers
      - name: Run tests
        run: xcodebuild -scheme FHPropertyWrappers test
